version: '3'
services:
  setup:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: "['*']"
      DEBUG: "true"
      DATABASE_URL: "postgres://local:local@db:5432/ssapi"
      CORS_ALLOWED_ORIGINS: '["http://localhost:3000"]'
      SECRET_KEY: "django-insecure-tx0(q!lqq4qja4z#)608n=%n5yuu!qs8)6rzvza@kx@kilw9gi"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=ssapi
    ports:
      - "5432:5432"
